- type: entity
  id: CEBaseVehicleStrap
  abstract: true
  categories: [ ForkFiltered ]
  components:
  - type: Sprite
    noRot: true
  - type: InputMover
  - type: Clickable
  - type: InteractionOutline
  - type: Pullable
  - type: Physics
    bodyType: KinematicController
  - type: CEVehicle
    transferDamage: false
  - type: CEStrapVehicle
  - type: Strap
  - type: MovementSpeedModifier
    weightlessModifier: 0
    acceleration: 2
    friction: 2
    frictionNoInput: 6
    baseWalkSpeed: 4.5
    baseSprintSpeed: 6
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.4
        density: 360
        restitution: 0.0
        mask:
        - MobMask
        layer:
        - TableLayer
  - type: Tag
    tags:
    - DoorBumpOpener
    - FootstepSound