- type: entity
  id: CEWheat
  parent: FoodInjectableBase
  name: wheat bushel
  description: You have the choice of either planting the grains again or grinding them into flour.
  categories: [ ForkFiltered ]
  components:
  - type: Item
    size: Tiny
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/wheat.rsi
    layers:
      - state: base1
        map: ["random"]
  - type: RandomSprite
    available:
    - random:
        base1: ""
        base2: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Flour
          Quantity: 5
  - type: Tag
    tags:
    - CEWheat
  - type: SliceableFood
    count: 2
    sliceTime: 1.5
    slice: CESeedWheat
  - type: StaticPrice
    price: 1

- type: entity
  id: CECotton
  parent: FoodInjectableBase
  name: cotton
  description: A plant raw fiber used to make cotton fabric.
  categories: [ ForkFiltered ]
  components:
  - type: Item
    size: Tiny
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/cotton.rsi
    layers:
      - state: base1
        map: ["random"]
  - type: RandomSprite
    available:
    - random:
        base1: ""
        base2: ""
        base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Fiber
          Quantity: 5
  - type: SliceableFood
    count: 3
    sliceTime: 1.5
    slice: CESeedCotton
  - type: StaticPrice
    price: 1

- type: entity
  id: CEFoodCabbage
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: cabbage
  description: Green edible ball.
  components:
  - type: Item
    size: Normal
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/cabbage.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 0.5
  - type: SliceableFood
    count: 4
    sliceTime: 1.5
    slice: CEFoodCabbageSlice
  - type: CEAdditionalSliceableDrop
    loot:
      CESeedCabbage: 1
  - type: Tag
    tags:
    - CEVegetable
    - CESalad
    - CECabbage

- type: entity
  id: CEFoodCabbageSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: cabbage leaf
  description: Time to make green salads.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/cabbage.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
          slice2: ""
          slice3: ""
          slice4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3 # 1/4 cabbage
        reagents:
        - ReagentId: Nutriment
          Quantity: 0.83
        - ReagentId: Vitamin
          Quantity: 0.14
  - type: Tag
    tags:
    - CEVegetable
    - CESalad
    - CECabbage

- type: entity
  id: CEFoodPumpkin
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: pumpkin
  description: Big, cool pumpkin.
  components:
  - type: Item
    size: Normal
  - type: FlavorProfile
    flavors:
      - pumpkin
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/pumpkin.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: PumpkinFlesh
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 2
  - type: SliceableFood
    count: 5
    sliceTime: 2
    slice: CEFoodPumpkinSlice
  - type: CEAdditionalSliceableDrop
    loot:
      CESeedPumpkin: 1
  - type: Tag
    tags:
    - CEVegetable
    - CEPumpkin

- type: entity
  id: CEFoodPumpkinSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: pumpkin slice
  description: Sliced pumpkin, ready to be cooked or eaten raw.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - pumpkin
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/pumpkin.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
          slice2: ""
          slice3: ""
          slice4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 6 # 1/5 pumpkin
        reagents:
        - ReagentId: PumpkinFlesh
          Quantity: 1.33
        - ReagentId: Vitamin
          Quantity: 0.57
  - type: Tag
    tags:
    - CEVegetable
    - CEPumpkin

- type: entity
  id: CEFoodPotato
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: potato
  description: Cute potato.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - potatoes
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/potato.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 2.33
        - ReagentId: Vitamin
          Quantity: 1.14
  - type: CESeed
    plantProto: CEPlantPotato #TODO sliceable potato
  - type: Temperature
    currentTemperature: 290
  - type: InternalTemperature
    thickness: 0.006
    area: 0.006
  #- type: CETemperatureTransformation
  #  entries:
  #  - temperatureRange: 400, 500
  #    transformTo: CEFoodPotatoHot
  - type: Tag
    tags:
    - CEVegetable
    - CEPotato

- type: entity
  id: CEFoodCucumber
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: cucumber
  description: An oblong green vegetable. Refreshing!
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - CEWater
      - CEcucumber
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/cucumber.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 1.33
        - ReagentId: Vitamin
          Quantity: 1.14
        - ReagentId: Water
          Quantity: 3
  - type: SliceableFood
    count: 2
    sliceTime: 1
    slice: CEFoodCucumberSlice
  - type: CEAdditionalSliceableDrop
    loot:
      CESeedCucumber: 1
  - type: Tag
    tags:
    - CEVegetable

- type: entity
  id: CEFoodCucumberSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: cucumber slice
  description: An evenly cut cucumber, still as green and watery.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - CEWater
      - CEcucumber
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/cucumber.rsi
    layers:
      - state: slice1
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 1
        - ReagentId: Water
          Quantity: 1.5
  - type: Tag
    tags:
    - CEVegetable

- type: entity
  id: CEFoodTomatoes
  parent: [FoodInjectableBase, ItemHeftyBase]
  categories: [ ForkFiltered ]
  name: tomatoes
  description: A red, juicy tomato. You just want to throw it in someone's face!
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - tomato
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/tomato.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 1
        - ReagentId: Vitamin
          Quantity: 1.71
        - ReagentId: JuiceTomato
          Quantity: 6
  - type: SliceableFood
    count: 3
    sliceTime: 1
    slice: CEFoodTomatoesSlice
  - type: CEAdditionalSliceableDrop
    loot:
      CESeedTomato: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Extractable
    grindableSolutionName: food
    juiceSolution:
      reagents:
      - ReagentId: JuiceTomato
        Quantity: 10
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Tag
    tags:
    - CEVegetable

- type: entity
  id: CEFoodTomatoesSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: tomato slice
  description: Thin red tomato slice. It's no longer as nice to throw at people as whole tomatoes.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - tomato
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/tomato.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3 # 1/3 pumpkin
        reagents:
        - ReagentId: Nutriment
          Quantity: 0.33
        - ReagentId: Vitamin
          Quantity: 0.57
  - type: Tag
    tags:
    - CEVegetable

- type: entity
  id: CEFoodApple
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: apple
  description: A fruit for lovers of a quick snack.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - apple
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: Nutriment
          Quantity: 3.33
        - ReagentId: Vitamin
          Quantity: 2.29
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/apple.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceApple
        Quantity: 12
  - type: SliceableFood
    count: 4
    sliceTime: 1.5
    slice: CEFoodAppleSlice
  - type: Tag
    tags:
    - CEFruits

- type: entity
  parent: CEFoodApple
  id: CEFoodAppleFalling #Fun falling from sky apples
  suffix: Falling
  components:
  - type: CEZPhysics
    localPosition: 0.99

- type: entity
  id: CEFoodAppleSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: apple slice
  description: Small slices to eat at one time.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - apple
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/apple.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
          slice2: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 4
        reagents:
        - ReagentId: Nutriment
          Quantity: 0.83
        - ReagentId: Vitamin
          Quantity: 0.57
  - type: Tag
    tags:
    - CEFruits

- type: entity
  id: CEFoodPepper
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: pepper
  description: Red and sweetish.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - peppery
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/pepper.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SliceableFood
    count: 4
    sliceTime: 2
    slice: CEFoodPepperSlice
  - type: CEAdditionalSliceableDrop
    loot:
      CESeedPepper: 1
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: Nutriment
          Quantity: 2.67
        - ReagentId: Vitamin
          Quantity: 3.43
  - type: Tag
    tags:
    - CEVegetable

- type: entity
  id: CEFoodPepperSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: pepper slice
  description: Still as red and sweetish.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - peppery
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/pepper.rsi
    layers:
      - state: slice1
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3.5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 1
  - type: Tag
    tags:
    - CEVegetable

- type: entity
  id: CEFoodOnion
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: onion
  description: If you eat too much, you can cry tears of joy.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - onion
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/onion.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 17
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 2.29
        - ReagentId: Allicin
          Quantity: 3
  - type: SliceableFood
    count: 4
    sliceTime: 2
    slice: CEFoodOnionSlice
  - type: CESeed
    plantProto: CEPlantOnion
  - type: Tag
    tags:
    - CEVegetable

- type: entity
  id: CEFoodOnionSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: onion ring
  description: A more tolerable and easy to eat onion ring.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - onion
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/onion.rsi
    layers:
      - state: slice1
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2.2
        - ReagentId: Vitamin
          Quantity: 1
        - ReagentId: Allicin
          Quantity: 0.8
  - type: Tag
    tags:
    - CEVegetable

- type: entity
  id: CEFoodChanterelle
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: chanterelle
  description: A delicious mushroom.
  components:
  - type: Item
    size: Tiny
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/chanterelle.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
          base5: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 2.33
        - ReagentId: Vitamin
          Quantity: 1.14
  - type: CESeed
    plantProto: CEPlantChanterelle
  - type: Temperature
    currentTemperature: 290
  - type: InternalTemperature
    thickness: 0.006
    area: 0.006

- type: entity
  id: CEFoodSunflowerHead
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: sunflower head
  description: A cut flower from a cheerful, sun-loving plant. Inside are lots of delicious seeds.
  components:
  - type: Item
    size: Tiny
    shape:
    - 0, 0, 0, 1
  - type: Sprite
    sprite: _CE/Objects/Consumable/Food/sunflower.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 2
  - type: SliceableFood
    count: 3
    sliceTime: 3
    slice: CESeedSunflower
  - type: Temperature
    currentTemperature: 290
  - type: InternalTemperature
    thickness: 0.006
    area: 0.006
